[package]
authors = ["Jacob Brown <j.h.brown@tcu.edu>"]
build = "build.rs"
name = "gmagick"
version = "0.1.1"

[build-dependencies]
bindgen = "0.30"
pkg-config = "0.3.9"

[dependencies]
failure = "0.1.0"
failure_derive = "0.1.0"
libc = "0.2.33"
