[package]
name = "gmagick"
version = "0.1.1"
authors = ["Jacob Brown <j.h.brown@tcu.edu>"]

build = "build.rs"

[dependencies]
libc    = "*"

[build-dependencies]
pkg-config = "*"
bindgen = { git = "https://github.com/crabtw/rust-bindgen#1b50ffed" }

