[package]
authors = ["Jacob Brown <j.h.brown@tcu.edu>"]
build = "build.rs"
name = "gmagick"
version = "0.1.1"

[build-dependencies]
bindgen = "0.16.0"
pkg-config = "0.3.8"

[dependencies]
libc = "0.2.9"
